### ISSUE TITLE
Advanced kits mod won't work

### ISSUE THREAD

**Issue by REALZulfikar** [ScerIO/PocketMine-MP-Android#138] opened 2020-01-06 20:41 UTC
I don't now why this mod won't work because it used to work in the past I tried fixing it but could not find the answer so please help me on this. Here's the proof [20:30:24] [Server thread/INFO]: Enabling AdvancedKits v5.2.3
[20:30:24] [Server thread/NOTICE]: [AdvancedKits] PiggyCustomEnchants detected. Activated custom enchants support
[20:30:24] [Server thread/NOTICE]: [AdvancedKits] FormAPI detected. Activated kit selection UI support
[20:30:24] [Server thread/CRITICAL]: Error: "Call to a member function getSize() on array" (EXCEPTION) in "src/pocketmine/item/enchantment/Enchantment" at line 158
[20:30:24] [Server thread/DEBUG]: #0 src/pocketmine/item/enchantment/Enchantment(172): pocketmine\item\enchantment\Enchantment::getEnchantment(integer 9)
[20:30:24] [Server thread/DEBUG]: #1 plugins/AdvancedKits.phar/src/AdvancedKits/Kit(218): pocketmine\item\enchantment\Enchantment::getEnchantmentByName(string[9] sharpness)
[20:30:24] [Server thread/DEBUG]: #2 plugins/AdvancedKits.phar/src/AdvancedKits/Kit(52): AdvancedKits\Kit->loadItem(string[39] 276:0:1:..4OVERLORD'S Sword:sharpness:6)
[20:30:24] [Server thread/DEBUG]: #3 plugins/AdvancedKits.phar/src/AdvancedKits/Main(129): AdvancedKits\Kit->__construct(object AdvancedKits\Main, array[15], string[11] ..4OVERLORD)
[20:30:24] [Server thread/DEBUG]: #4 plugins/AdvancedKits.phar/src/AdvancedKits/Main(45): AdvancedKits\Main->loadKits()
[20:30:24] [Server thread/DEBUG]: #5 src/pocketmine/plugin/PluginBase(123): AdvancedKits\Main->onEnable()
[20:30:24] [Server thread/DEBUG]: #6 src/pocketmine/plugin/PluginManager(581): pocketmine\plugin\PluginBase->setEnabled(boolean 1)
[20:30:24] [Server thread/DEBUG]: #7 src/pocketmine/Server(1999): pocketmine\plugin\PluginManager->enablePlugin(object AdvancedKits\Main)
[20:30:24] [Server thread/DEBUG]: #8 src/pocketmine/Server(1985): pocketmine\Server->enablePlugin(object AdvancedKits\Main)
[20:30:24] [Server thread/DEBUG]: #9 src/pocketmine/Server(1783): pocketmine\Server->enablePlugins(integer 1)
[20:30:24] [Server thread/DEBUG]: #10 src/pocketmine/PocketMine(268): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[34] /storage/emulated/0/PocketMine-MP/, string[42] /storage/emulated/0/PocketMine-MP/plugins/)
[20:30:24] [Server thread/DEBUG]: #11 src/pocketmine/PocketMine(291): pocketmine\server()
[20:30:24] [Server thread/DEBUG]: #12 (1): require(string[89] phar:///storage/emulated/0/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/Pocke)
[20:30:24] [Server thread/INFO]: Disabling AdvancedKits v5.2.3 that's all I found it said about it

**Comment by SergeShkurko** [comment] 2020-01-07 18:48
Duplicate of #83

**Closed by SergeShkurko** 2020-01-07 18:48 UTC

**Comment by REALZulfikar** [comment] 2020-01-08 21:25
It's not the same!

**Comment by Rayter26** [comment] 2020-01-09 00:10
Rip dude
