### ISSUE TITLE
Kernel support in src folder (Google Translate)

### ISSUE THREAD

**Issue by cprytik11** [ScerIO/PocketMine-MP-Android#33] opened 2019-05-09 17:04 UTC
Good afternoon, please add kernel support in the form of a src folder!  Sorry if there are errors here, I am Russian and used Google Translate to write my request ...

**Comment by Frago9876543210** [comment] 2019-05-09 17:50
Duplicate of #2

**Closed** 2019-05-09 17:50 UTC
Labels: duplicate
